### ISSUE TITLE
建立不了连接

### ISSUE THREAD

**Issue by stonexing** [dake/SimpleTunnelCustomizedNetworkingUsingtheNetworkExtensionFramework#3]
我之前也做到这一步了 但是建立不了连接
手机端代码无需修改 
 tunnel_server用旧版xcode编译通过连不上vpn
然后又改为swift3.0修改很多代码 
最终还是同样的问题
命令行里只收到提示Accepted a new connection
但连不上vpn

**Comment by FanLemon** [comment]
tunnel_server因为swift 3语法升级有个bug。我修改后可以正常收到手机端的ip packet。

**Comment by dake** [comment]
@FanLemon 感谢。。能提个PR 吗？
